export const FETCH_HOMEMADE_MEAL_LIST_START = 'FETCH_HOMEMADE_MEAL_LIST_START';
export const FETCH_HOMEMADE_MEAL_LIST_SUCCESS = 'FETCH_HOMEMADE_MEAL_LIST_SUCCESS';
export const FETCH_HOMEMADE_MEAL_LIST_FAIL = 'FETCH_HOMEMADE_MEAL_LIST_FAIL';

export const FETCH_OUTSIDE_MEAL_LIST_START = 'FETCH_OUTSIDE_MEAL_LIST_START';
export const FETCH_OUTSIDE_MEAL_LIST_SUCCESS = 'FETCH_OUTSIDE_MEAL_LIST_SUCCESS';
export const FETCH_OUTSIDE_MEAL_LIST_FAIL = 'FETCH_OUTSIDE_MEAL_LIST_FAIL';

export const CREATE_HOMEMADE_MEAL_START = 'CREATE_HOMEMADE_MEAL_START';
export const CREATE_HOMEMADE_MEAL_SUCCESS = 'CREATE_HOMEMADE_MEAL_SUCCESS';
export const CREATE_HOMEMADE_MEAL_FAIL = 'CREATE_HOMEMADE_MEAL_FAIL';

export const CREATE_OUTSIDE_MEAL_START = 'CREATE_OUTSIDE_MEAL_START';
export const CREATE_OUTSIDE_MEAL_SUCCESS = 'CREATE_OUTSIDE_MEAL_SUCCESS';
export const CREATE_OUTSIDE_MEAL_FAIL = 'CREATE_OUTSIDE_MEAL_FAIL';

export const UPDATE_HOMEMADE_MEAL_START = 'UPDATE_HOMEMADE_MEAL_START';
export const UPDATE_HOMEMADE_MEAL_SUCCESS = 'UPDATE_HOMEMADE_MEAL_SUCCESS';
export const UPDATE_HOMEMADE_MEAL_FAIL = 'UPDATE_HOMEMADE_MEAL_FAIL';

export const UPDATE_OUTSIDE_MEAL_START = 'UPDATE_OUTSIDE_MEAL_START';
export const UPDATE_OUTSIDE_MEAL_SUCCESS = 'UPDATE_OUTSIDE_MEAL_SUCCESS';
export const UPDATE_OUTSIDE_MEAL_FAIL = 'UPDATE_OUTSIDE_MEAL_FAIL';

export const SET_CURRENT_HOMEMADE_MEAL = 'SET_CURRENT_HOMEMADE_MEAL';

export const SET_CURRENT_OUTSIDE_MEAL = 'SET_CURRENT_OUTSIDE_MEAL';

export const DELETE_HOMEMADE_MEAL_START = 'DELETE_HOMEMADE_MEAL_START';
export const DELETE_HOMEMADE_MEAL_SUCCESS = 'DELETE_HOMEMADE_MEAL_SUCCESS';
export const DELETE_HOMEMADE_MEAL_FAIL = 'DELETE_HOMEMADE_MEAL_FAIL';

export const DELETE_OUTSIDE_MEAL_START = 'DELETE_OUTSIDE_MEAL_START';
export const DELETE_OUTSIDE_MEAL_SUCCESS = 'DELETE_OUTSIDE_MEAL_SUCCESS';
export const DELETE_OUTSIDE_MEAL_FAIL = 'DELETE_OUTSIDE_MEAL_FAIL';

export const FETCH_TAGS_START = 'FETCH_TAGS_START';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAIL = 'FETCH_TAGS_FAIL';

export const FETCH_CITY_COUNTRY_LIST_START = 'FETCH_CITY_COUNTRY_LIST_START';
export const FETCH_CITY_COUNTRY_LIST_SUCCESS = 'FETCH_CITY_COUNTRY_LIST_SUCCESS';
export const FETCH_CITY_COUNTRY_LIST_FAIL = 'FETCH_CITY_COUNTRY_LIST_FAIL';

export const FETCH_USERDETAILS_START = 'FETCH_USERDETAILS_START';
export const FETCH_USERDETAILS_SUCCESS = 'FETCH_USERDETAILS_SUCCESS';
export const FETCH_USERDETAILS_FAIL = 'FETCH_USERDETAILS_FAIL';

export const SET_USER_PREFERECES_START = 'SET_USER_PREFERECES_START';
export const SET_USER_PREFERECES_SUCCESS = 'SET_USER_PREFERECES_SUCCESS';
export const SET_USER_PREFERECES_FAIL = 'SET_USER_PREFERECES_FAIL';

export const EXPLORE_FETCH_HOMEMADE_MEAL_LIST_START = 'EXPLORE_FETCH_HOMEMADE_MEAL_LIST_START';
export const EXPLORE_FETCH_HOMEMADE_MEAL_LIST_SUCCESS = 'EXPLORE_FETCH_HOMEMADE_MEAL_LIST_SUCCESS';
export const EXPLORE_FETCH_HOMEMADE_MEAL_LIST_FAIL = 'EXPLORE_FETCH_HOMEMADE_MEAL_LIST_FAIL';

export const EXPLORE_FETCH_OUTSIDE_MEAL_LIST_START = 'EXPLORE_FETCH_OUTSIDE_MEAL_LIST_START';
export const EXPLORE_FETCH_OUTSIDE_MEAL_LIST_SUCCESS = 'EXPLORE_FETCH_OUTSIDE_MEAL_LIST_SUCCESS';
export const EXPLORE_FETCH_OUTSIDE_MEAL_LIST_FAIL = 'EXPLORE_FETCH_OUTSIDE_MEAL_LIST_FAIL';
